# Generated by Django 4.0.4 on 2022-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='api',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='persistence',
        ),
        migrations.AddField(
            model_name='project',
            name='size',
            field=models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small')], default='medium', max_length=20, verbose_name='Size'),
        ),
    ]
