# Generated by Django 3.1.1 on 2022-04-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0003_auto_20220428_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hacks.api')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hacks.client')),
                ('persistence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hacks.persistence')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hacks.project')),
            ],
        ),
    ]
